# Generated by Django 5.2.17 on 2026-08-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('cancelled', 'Cancelada')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='catalog.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='screening.room')),
            ],
            options={
                'verbose_name': 'sessão',
                'verbose_name_plural': 'sessões',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='idx_sessao_status_inicio')],
                'constraints': [models.UniqueConstraint(fields=('room', 'starts_at'), name='uma_sessao_por_sala_e_horario')],
            },
        ),
    ]
