# Generated by Django 5.2.17 on 2026-08-11 19:45
#
# Os três modelos e a constraint `unico_assento_por_sessao` estão nesta
# MESMA migração de propósito. Separá-los — modelo numa, constraint noutra —
# deixaria uma janela em que existe escrita de ocupação de assento sem a
# garantia que a protege, e é literalmente o que o Princípio II proíbe.
#
# Se um dia esta migração for dividida, a divisão é o defeito.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('held', 'Reservada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='screening.screening')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('common', 'Comum'), ('accessible', 'Acessibilidade')], default='common', max_length=16)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screening.room')),
            ],
            options={
                'verbose_name': 'assento',
                'verbose_name_plural': 'assentos',
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ReservedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='screening.reservation')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_seats', to='screening.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations', to='screening.seat')),
            ],
            options={
                'verbose_name': 'assento reservado',
                'verbose_name_plural': 'assentos reservados',
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'row', 'number'), name='unico_lugar_por_posicao_na_sala'),
        ),
        migrations.AddConstraint(
            model_name='reservedseat',
            constraint=models.UniqueConstraint(fields=('screening', 'seat'), name='unico_assento_por_sessao'),
        ),
    ]
