# Generated by Django 5.2.17 on 2026-08-12 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_reservation_seat_reservedseat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('held', 'Reservada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('paid', 'Paga')], default='held', max_length=12),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('declined', 'Recusado')], max_length=12)),
                ('decline_reason', models.CharField(blank=True, choices=[('saldo_insuficiente', 'Saldo insuficiente'), ('cartao_expirado', 'Cartão expirado'), ('recusado_pelo_emissor', 'Recusado pelo emissor')], default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='screening.reservation')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='screening.payment')),
                ('reserved_seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='screening.reservedseat')),
            ],
            options={
                'verbose_name': 'ingresso',
                'verbose_name_plural': 'ingressos',
                'ordering': ['reserved_seat__seat__row', 'reserved_seat__seat__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('reservation',), name='um_pagamento_aprovado_por_reserva'),
        ),
    ]
