# Generated by Django 5.2.17 on 2026-08-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_alter_reservation_status_payment_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='screening.ticket')),
            ],
            options={
                'verbose_name': 'link de compartilhamento',
                'verbose_name_plural': 'links de compartilhamento',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('ticket',), name='um_link_ativo_por_ingresso')],
            },
        ),
    ]
