# Generated by Django 5.2.17 on 2026-08-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_ticketsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
