# Generated by Django 5.2.17 on 2026-08-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'gênero',
                'verbose_name_plural': 'gêneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.TextField(blank=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('certification_br', models.CharField(blank=True, max_length=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre')),
            ],
            options={
                'verbose_name': 'filme',
                'verbose_name_plural': 'filmes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=20)),
                ('external_key', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('kind', models.CharField(choices=[('trailer', 'Trailer'), ('teaser', 'Teaser')], default='trailer', max_length=20)),
                ('is_official', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='catalog.movie')),
            ],
            options={
                'verbose_name': 'trailer',
                'verbose_name_plural': 'trailers',
                'constraints': [models.UniqueConstraint(fields=('movie', 'provider', 'external_key'), name='unique_trailer_por_filme_e_provedor'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('movie',), name='unico_trailer_primario_por_filme')],
            },
        ),
    ]
