# Generated by Django 5.2.17 on 2026-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='catalog_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_upcoming',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
